# Generated by Django 5.2.7 on 2025-10-05 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_start_time', models.TimeField(blank=True, null=True)),
                ('sleep_end_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, help_text='Total sleep in hours', null=True)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any notes on sleep issues or factors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('relaxation', 'Relaxation'), ('routine', 'Routine'), ('environment', 'Environment')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
