# Generated by Django 6.0 on 2025-12-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sleeplog_tip_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='sleeplog',
            options={'verbose_name': 'Sleep Log', 'verbose_name_plural': 'Sleep Logs'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='duration_hours',
            field=models.FloatField(blank=True, help_text='Total sleep in hours', null=True, verbose_name='Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes on sleep issues or factors', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='sleep_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Sleep end time'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='sleep_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Sleep start time'),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('relaxation', 'Relaxation'), ('routine', 'Routine'), ('environment', 'Environment')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
